### ISSUE TITLE
new install fails on dayjs import

### ISSUE THREAD

**Issue by Joren-vanGoethem** [dickwolff/Export-To-Ghostfolio#64] opened 2024-05-05 08:27 UTC
i tried running the degiro exporter both by using dockerfile and by running it without dockerfile, both gave same error.

i used release 0.12.0 and the latest main branch, both failed
OS: Windows 11
Nodejs version used when running without dockerfile: 20.11.1

node:internal/process/esm_loader:34
      internalBinding('errors').triggerUncaughtException(
                                ^
Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:\Users\jovangoe\Downloads\Export-To-Ghostfolio\node_modules\dayjs\plugin\customParseFormat' imported from C:\Users\jovangoe\Downloads\Export-To-Ghostfolio\src\converters\degiroConverter.ts
Did you mean to import dayjs/plugin/customParseFormat.js?
    at finalizeResolution (node:internal/modules/esm/resolve:264:11)
    at moduleResolve (node:internal/modules/esm/resolve:917:10)
    at defaultResolve (node:internal/modules/esm/resolve:1130:11)
    at nextResolve (node:internal/modules/esm/hooks:865:28)
    at S (file:///C:/Users/jovangoe/Downloads/Export-To-Ghostfolio/node_modules/tsx/dist/esm/index.mjs?1714897062814:2:2951)
    at nextResolve (node:internal/modules/esm/hooks:865:28)
    at Hooks.resolve (node:internal/modules/esm/hooks:303:30)
    at handleMessage (node:internal/modules/esm/worker:196:24)
    at Immediate.checkForMessages [as _onImmediate] (node:internal/modules/esm/worker:138:28)
    at process.processImmediate (node:internal/timers:478:21) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///C:/Users/jovangoe/Downloads/Export-To-Ghostfolio/node_modules/dayjs/plugin/customParseFormat'
}

**Comment by dickwolff** [comment] 2024-05-05 08:31
Can you try and run `npm install` and then try to run the tool again?

**Comment by dickwolff** [comment] 2024-05-05 10:33
@Joren-vanGoethem See the comments on #65 for a quick fix. Will look into a definitive fix later.

Closing because duplicate of #65 and that issue has more details

**Closed by dickwolff** 2024-05-05 10:33 UTC
